### ISSUE TITLE
Morning Session Feedback

### ISSUE THREAD

**Issue by MasterLeiva** [CobbyElsonfx/Portfolio-Website#30]
Great code @CobbyElsonfx! I will like to give you some tips to better improve your code...

- [ ] Try to use more comments to make your code more readable and organized
- [ ] Try adding more padding to your headline section, it looks a little compressed without much padding

**Comment by BenMKT** [comment]
- Great Code 👏🏼. The layout is well-designed and very readable.
- I think it would be easier to change the `src` attribute for the project images directly in CSS rather than duplicating code in HTML.
